### ISSUE TITLE
InvalidArgument

### ISSUE THREAD

**Issue by hefeng1208** [mrrtree/egg-aws-s3#1]
hi~ 
我在使用本插件时，按照您写的usage发现报错。
error-message如下：
```
 InvalidArgument: InvalidArgument
    at Request.extractError (E:\work\FE\storage-back\node_modules\aws-sdk\lib\services\s3.js:577:35)
    at Request.callListeners (E:\work\FE\storage-back\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (E:\work\FE\storage-back\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (E:\work\FE\storage-back\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (E:\work\FE\storage-back\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (E:\work\FE\storage-back\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at E:\work\FE\storage-back\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (E:\work\FE\storage-back\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (E:\work\FE\storage-back\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (E:\work\FE\storage-back\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
  message: 'InvalidArgument',
  code: 'InvalidArgument',
  region: null,
```
config.default.js

````
config.awsS3= {
    client: {
      endpoint: 'xxx',
      accessKeyId: 'xxxx',
      secretAccessKey: 'xxx',
      region: 'xxx'
    },
  }
调用方式

try {
      const data = await this.app.awsS3.listBucketsAsync({});
      console.log(data);
    } catch (err) {
      console.log(err);
    }
```

请问是我的配置有问题吗？不太确定。。。能否指导一下。多谢~

**Comment by hefeng1208** [comment]
resloved it
